# Generated by Django 5.2 on 2025-04-24 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Palavra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palavra_ingles', models.CharField(max_length=100)),
                ('significado_portugues', models.CharField(max_length=100)),
            ],
        ),
    ]
