# Generated by Django 5.2 on 2025-04-24 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='palavra',
            old_name='palavra_ingles',
            new_name='ingles',
        ),
        migrations.RenameField(
            model_name='palavra',
            old_name='significado_portugues',
            new_name='portugues',
        ),
    ]
