# Generated by Django 5.2 on 2025-04-25 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='palavra',
            name='nivel',
            field=models.CharField(choices=[('facil', 'Fácil'), ('medio', 'Médio'), ('dificil', 'Difícil'), ('muito_dificil', 'Muito Difícil')], default='facil', max_length=20),
        ),
    ]
