# Generated by Django 5.2 on 2025-04-25 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_palavra_nivel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='palavra',
            old_name='palavra_ingles',
            new_name='ingles',
        ),
        migrations.RenameField(
            model_name='palavra',
            old_name='significado_portugues',
            new_name='portugues',
        ),
        migrations.RemoveField(
            model_name='palavra',
            name='nivel',
        ),
        migrations.AddField(
            model_name='palavra',
            name='dificuldade',
            field=models.CharField(choices=[('facil', 'Fácil'), ('medio', 'Médio'), ('dificil', 'Difícil')], default='facil', max_length=10),
            preserve_default=False,
        ),
    ]
